name: salat_time_and_slide
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  intl: ^0.17.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  flutter_screenutil: ^5.9.0
  smooth_compass: ^2.0.17
  google_maps_flutter: ^2.3.0
  lottie: ^2.3.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/